name: LaTeX Build

on:
  push:
    paths:
      - "*.tex"
      - "*.ttf"
      - ".github/workflows/*"
      - "*.md"
      - "**/*.md"

jobs:
  build:
    runs-on: ubuntu-latest
    container: thomasweise/docker-texlive-full

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install TexLive and other dependencies
      run: |
        apt-get update -qq
        # apt-get install -y texlive-full
        apt-get install -y latexmk pandoc

    - name: Copy fonts and update font cache
      run: |
        cp -v *.ttf /usr/local/share/fonts
        fc-cache -fv

    - name: Build LaTeX files
      run: |
        make convert
        make

    - id: commit
      uses: prompt/actions-commit-hash@v3
    - name: Upload PDF artifacts
      uses: actions/upload-artifact@v2
      with:
        name: pdf-files
        path: |
          *.pdf

    - name: Release
      uses: softprops/action-gh-release@v2 # in the future, try ncipollo/release-action@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.commit.outputs.short }}
        name: Release ${{ steps.commit.outputs.short }}
        draft: false
        prerelease: false
        files: |
          *.pdf
